### PR TITLE
Run tests as part of CI

### PR DESCRIPTION
**Pull request by cubisttriangle**
Run tests as part of CI.

This requires the following:
- Go to repository Settings -> Environment
- Create new environment with the name `build_test`
- Add an environment secret with the name `TEST_API_KEY` and set its value to your finnhub api key
- Do not specify any deployment branches. That way the environment can be available to all branches.

Also, when merging this, lets try a squash commit instead of a merge commit to see if the history looks any cleaner.

### CODE REVIEW

**Review by henryboisdequin — APPROVED** [review]
Thanks, I've followed your steps!

**Comment by henryboisdequin** [comment]
Yeah the squash and merge looks cleaner in my history

**Comment by cubisttriangle** [comment]
I agree - much better. Can you rerun the action to see if it succeeds?

**Comment by cubisttriangle** [comment]
Hm. The environment seems to work since the create_client test succeeded, but some of the other tests failed. I wonder if the max requests for the api key was exceeded. Maybe the sandbox api key would work?

**Comment by henryboisdequin** [comment]
Yes I agree, I'm going to test it

**Comment by henryboisdequin** [comment]
Hmm, looks like it's not related to that

**Comment by cubisttriangle** [comment]
Weird. I just ran locally after syncing with your main branch it worked. Also, the test [worked in my env](https://github.com/cubisttriangle/finnhub-rs/runs/2386731344?check_suite_focus=true). Maybe something is up with the github runners.

**Pull request merged**
